### ISSUE TITLE
Copy should make sure destination bitset has enough space

### ISSUE THREAD

**Issue by omerfirmak** [bits-and-blooms/bitset#130] opened 2023-06-23 17:18 UTC
https://github.com/bits-and-blooms/bitset/blob/38210554807e5c7ce64e035d266d77d84fd80e95/bitset.go#L562

`c.set` could be not large enough to hold the entire `b.set`

**Comment by lemire** [comment] 2023-06-23 18:14
Here is what the function is documented as doing...

```Go
// Copy into a destination BitSet using the Go array copy semantics:
// the number of bits copied is the minimum of the number of bits in the current
// BitSet (Len()) and the destination Bitset.
// We return the number of bits copied in the destination BitSet.
```

If you believe that this behaviour is not followed, please provide a test case.

If you prefer, you can call `CopyFull` which might what you are looking for.

Closing as "is as intended".

**Closed by lemire** 2023-06-23 18:14 UTC
